### ISSUE TITLE
Add PHP 8.0 support

### ISSUE THREAD

**Issue by AMartinNo1** [pagemachine/typo3-phinx#18]
At the moment PHP 8.0 is not supported.

https://github.com/pagemachine/typo3-phinx/blob/953fe50c32a7d8191b48fa52501ef04b8356ac49/composer.json#L13

https://www.php.net/supported-versions.php

Branch | Initial Release | Active Support Until | Security Support Until
-- | -- | -- | --
7.4 | 28 Nov 2019 | 2 years, 1 month ago | 28 Nov 2021 | 1 month ago | 28 Nov 2022 | in 10 months
8.0 | 26 Nov 2020 | 1 year, 1 month ago | 26 Nov 2022 | in 10 months | 26 Nov 2023 | in 1 year, 10 months
8.1 | 25 Nov 2021 | 1 month ago | 25 Nov 2023 | in 1 year, 10 months | 25 Nov 2024 | in 2 years, 10 months

**Comment by mbrodala** [comment]
I may be able to add this soon unless you beat me to it.

**Comment by AMartinNo1** [comment]
https://github.com/cakephp/phinx/blob/ad056cff354fc67fedf9bf96c441c2b428afad0c/composer.json#L39

This means, it can be used with PHP 8.0, right? So, we don't have any blocker there.

I can create a draft MR today, which adds PHP 8.0 to the CI & composer.json. We can continue from there then.
