### ISSUE TITLE
Add DB schema of phinx

### ISSUE THREAD

**Issue by nostadt** [pagemachine/typo3-phinx#20]
While cleaning up the DB of a TYPO3 instance I have noticed that the DB analyzer wants to delete (rename first) the table `tx_phinx_log`. This is because this ext. does not ship an `ext_tables.sql`.

I am aware that it does ease the maintenance, by not shipping it. However, it is crucial IMO that this table exist. So, my question: Should the schema be shipped along with that ext.?

I have mixed feelings towards that, because copying the schema is redundant.

**Comment by mbrodala** [comment]
Yes, this is definitely on my should-have list for a long time already. As you correctly point out shipping the schema statically would be redundant and prune to errors whenever Phinx changes something internally.

So maybe an approach would be to listen to the [`AlterTableDefinitionStatementsEvent`](https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/Hooks/Events/Core/Database/AlterTableDefinitionStatementsEvent.html) and inject the Phinx table schema this way. The schema must be fetched from Phinx itself here.

This would allow for updates by TYPO3 and have the Phinx table marked as known / in sync in TYPO3. However, I'm not sure if this will lead to issues with runtime migrations Phinx performs on this table itself. E.g. Phinx could check for the existence or setup of a column and skip an essential migration if it thinks the desired state is already reached. Even if this was only done by a basic schema update from TYPO3.

**Comment by AMartinNo1** [comment]
I see. Cool. Sounds interesting and appreciate the quick response. Unfortunately I cannot say anything about whether it would work or not.

**Comment by mbrodala** [comment]
@nostadt Can you test if #28 works for you? Here the `tx_phinx_log` table is gone from `table.prefix` / `Prefix tables` afterwards, thus left unchanged.

**Comment by mbrodala** [comment]
(Successfully tested with TYPO3v10 and TYPO3v11 so I'll merge and release this fix.)
