### ISSUE TITLE
Exception when database port is not specified

### ISSUE THREAD

**Issue by dahaupt** [pagemachine/typo3-phinx#38]
An exception occurs in case `$GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default']['port']` is not specified:
```
[ TYPO3\CMS\Core\Error\Exception ]                                                                                                            
  PHP Warning: Undefined array key "port" in /var/www/html/vendor/pagemachine/typo3-phinx/Classes/Configuration/PhinxConfiguration.php line 34
```

We generally do not configure this value as the default value of `3306` is used as a fallback within Doctrine DBAL.

**Comment by mbrodala** [comment]
Can you verify that https://github.com/pagemachine/typo3-phinx/pull/39 fixes this?

**Comment by mbrodala** [comment]
New release: https://github.com/pagemachine/typo3-phinx/releases/tag/1.1.7
